---
title: Disturbance Term - Test
author: Davi Simon
date: '2019-07-09'
keywords: tech
slug: disturbance-term-test
tags: 
- lindia
categories: 
- Finance 
- R
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```


```{r c1, echo=FALSE, message=FALSE, include=FALSE}
library(dplyr)
library(readxl)
library(writexl)
library(stringr)
library(tidyverse)
library(rstudioapi)
library(magrittr)
library(tidyverse)
library(ggplot2)
require(lindia)
library(knitr)
library(kableExtra)

```


Differences of disturbance terms at the population level and residuals from multivariate OLS. 

Inspired by: 
https://github.com/Matzge/Simulation-Error-Term-and-Residuals


## TRUE MODEL

```{r c2}

set.seed(1)

X1 <- rnorm(1000, mean = 500, sd=10)

X2 <- rnorm(1000, mean = 250, sd=10)

X3 <- rnorm(1000, mean = 10, sd = 50)

u <- rnorm(1000, mean=0, sd=10)

Data <- cbind(X1,X2,X3,u)
Data <- as.data.frame(Data)

```



Creating the true model based on a deterministic function
```{r c3}
Data %<>% mutate(Y = (500 + 2.7*X1 + 0.44*X2 -0.12*X3 + u))
```


Summing and computing trhe mean of the disturbance
```{r c4, eval=TRUE}

sum(Data$u)
mean(Data$u)
```



Modelling
```{r c5, eval=TRUE }
Data %>% lm(Y ~ X1 + X2 + X3, data=.) %>% summary()
```

Checking the residuals
```{r c6, eval=TRUE} 
m1 <- lm(Y ~ X1 + X2 + X3, data=Data)
sum(m1$residuals)
mean(m1$residuals)
```


Diagnosing residuals
```{r c7, eval=TRUE }
gg_diagnose(m1)
```


Ploting residuals x disturbances
```{r c8, eval=TRUE}
Data <- cbind(Data, m1$residuals)
ggplot(Data) + geom_point(aes(x=u, y=`m1$residuals`))

```



that's it for today!